[package]
name = "wire-protocol"
version = "0.1.1"
edition = "2021"
description = "VLESS / Trojan / VMess framing over byte streams (Pirate gRPC ProxyTunnel)"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
uuid = { version = "1", features = ["v4", "serde"] }
sha2 = { workspace = true }
hex = { workspace = true }
aes-gcm = "0.10"
aes = "0.8"
md5 = "0.7"
rand = { workspace = true }
chrono = "0.4"
base64 = { workspace = true }
shadowsocks-crypto = { version = "0.5", default-features = false, features = ["v1-aead", "hkdf", "sha1", "aes-gcm", "chacha20poly1305"] }

[dev-dependencies]
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
