[package]
name = "deploy-server"
version = "0.1.8"
edition = "2021"

[dependencies]
deploy-auth = { path = "../deploy-auth" }
ed25519-dalek = "2"
parking_lot = { workspace = true }
deploy-core = { path = "../deploy-core" }
deploy-control = { path = "../deploy-control" }
deploy-db = { path = "../deploy-db" }
deploy-proto = { path = "../../proto" }
wire-protocol = { path = "../../wire-protocol" }
prost = { workspace = true }
tokio = { version = "1", features = ["macros", "rt-multi-thread", "fs", "io-util", "process", "sync", "net", "time"] }
tokio-stream = "0.1"
tonic = { version = "0.12", features = ["transport"] }
clap = { version = "4", features = ["derive", "env"] }
tracing = { workspace = true }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
sha2 = { workspace = true }
flate2 = { workspace = true }
tar = { workspace = true }
hex = { workspace = true }
futures-util = { workspace = true }
libc = { workspace = true }
argon2 = "0.5"
password-hash = "0.5"
serde = { workspace = true }
serde_json = { workspace = true }
chrono = { version = "0.4", features = ["clock"] }
chrono-tz = "0.9"
sysinfo = { workspace = true }
rand = { workspace = true }
uuid = { version = "1", features = ["v4"] }
redis = { version = "0.27", features = ["tokio-comp"] }
quinn = "0.11"
rustls = { version = "0.23", default-features = false, features = ["ring", "std"] }
rustls-pki-types = "1"
rcgen = "0.13"
rustls-pemfile = "2"
regex = "1"
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls"] }

[dev-dependencies]
tempfile = "3"
