#!/usr/bin/env bash
# Install Redis server with bind/port and auth (requirepass or ACL). Run as root.
# Env (optional): PIRATE_REDIS_BIND, PIRATE_REDIS_PORT, PIRATE_REDIS_AUTH_MODE (requirepass|acl),
# PIRATE_REDIS_PASSWORD, PIRATE_REDIS_ACL_USERNAME (acl mode).
set -euo pipefail
export DEBIAN_FRONTEND=noninteractive

BIND="${PIRATE_REDIS_BIND:-127.0.0.1}"
PORT="${PIRATE_REDIS_PORT:-6379}"
AUTH_MODE="${PIRATE_REDIS_AUTH_MODE:-requirepass}"
PASSWORD="${PIRATE_REDIS_PASSWORD:-}"
ACL_USER="${PIRATE_REDIS_ACL_USERNAME:-pirate_redis}"

if [[ "$AUTH_MODE" != "requirepass" && "$AUTH_MODE" != "acl" ]]; then
  echo "redis: PIRATE_REDIS_AUTH_MODE must be requirepass or acl (got: ${AUTH_MODE})" >&2
  exit 1
fi

if [[ "$AUTH_MODE" == "acl" ]]; then
  if [[ -z "${ACL_USER// }" ]]; then
    echo "redis: PIRATE_REDIS_ACL_USERNAME is required for acl mode" >&2
    exit 1
  fi
  if [[ ! "$ACL_USER" =~ ^[a-zA-Z][a-zA-Z0-9_-]*$ ]]; then
    echo "redis: PIRATE_REDIS_ACL_USERNAME must match ^[a-zA-Z][a-zA-Z0-9_-]*$" >&2
    exit 1
  fi
fi

if [[ -z "$PASSWORD" ]]; then
  if command -v openssl &>/dev/null; then
    PASSWORD="$(openssl rand -hex 24)"
  else
    PASSWORD="$(tr -dc 'a-f0-9' </dev/urandom | head -c 48)"
  fi
fi

if [[ "$AUTH_MODE" == "acl" ]] && [[ ! "$PASSWORD" =~ ^[a-zA-Z0-9_-]+$ ]]; then
  echo "redis: in ACL mode the password must match ^[a-zA-Z0-9_-]+$ (no spaces/special chars); use requirepass mode otherwise" >&2
  exit 1
fi

case "$PORT" in
'' | *[!0-9]*)
  echo "redis: PIRATE_REDIS_PORT must be a number" >&2
  exit 1
  ;;
esac
if ((PORT < 1 || PORT > 65535)); then
  echo "redis: invalid PIRATE_REDIS_PORT" >&2
  exit 1
fi

if [[ "$BIND" == *$'\n'* ]] || [[ "$BIND" == *$'\r'* ]]; then
  echo "redis: PIRATE_REDIS_BIND must be a single line" >&2
  exit 1
fi

if command -v ss &>/dev/null; then
  if ss -ltnH "sport = :$PORT" 2>/dev/null | grep -q .; then
    echo "redis: port $PORT is already in use (choose another PIRATE_REDIS_PORT or free the port)" >&2
    exit 1
  fi
fi

# Skip maintainer-script service start during apt (often fails if port busy or before our config); we start after writing conf.
POLICY_RC=/usr/sbin/policy-rc.d
POLICY_CREATED=0
policy_teardown() {
  if [[ "$POLICY_CREATED" == 1 ]] && [[ -f "$POLICY_RC" ]]; then
    rm -f "$POLICY_RC"
  fi
}
if [[ ! -e "$POLICY_RC" ]]; then
  install -d -m 0755 /usr/sbin
  printf '%s\n' '#!/bin/sh' 'exit 101' >"$POLICY_RC"
  chmod +x "$POLICY_RC"
  POLICY_CREATED=1
fi
trap policy_teardown EXIT

apt-get update -qq
apt-get install -y -qq redis-server

trap - EXIT
policy_teardown

REDIS_MAIN="${REDIS_MAIN_CONF:-/etc/redis/redis.conf}"
REDIS_FRAG=/etc/redis/pirate-stack-generated.conf
REDIS_ACL=/etc/redis/pirate-users.acl

escape_double() {
  local s="$1"
  s="${s//\\/\\\\}"
  s="${s//\"/\\\"}"
  printf '%s' "$s"
}

ESC_PASS="$(escape_double "$PASSWORD")"

{
  echo "# Generated by install-redis.sh — re-run host-service install to change."
  echo "bind ${BIND}"
  echo "port ${PORT}"
  echo "protected-mode yes"
} >"$REDIS_FRAG"

if [[ "$AUTH_MODE" == "requirepass" ]]; then
  printf 'requirepass "%s"\n' "$ESC_PASS" >>"$REDIS_FRAG"
  rm -f "$REDIS_ACL"
else
  # Redis 6.0 (Ubuntu redis-server): omit &* (pubsub all-channels) — not supported on all 6.0 builds.
  {
    echo "user default off"
    echo "user ${ACL_USER} on >${PASSWORD} ~* +@all"
  } >"$REDIS_ACL"
  chmod 0640 "$REDIS_ACL"
  if id redis &>/dev/null; then
    chown redis:redis "$REDIS_ACL" 2>/dev/null || true
  fi
  echo "aclfile ${REDIS_ACL}" >>"$REDIS_FRAG"
fi

chmod 0644 "$REDIS_FRAG"

if [[ -f "$REDIS_MAIN" ]]; then
  if ! grep -qF 'include /etc/redis/pirate-stack-generated.conf' "$REDIS_MAIN" 2>/dev/null; then
    {
      echo ""
      echo "# Pirate host-services (last wins over earlier bind/port/auth)"
      echo "include /etc/redis/pirate-stack-generated.conf"
    } >>"$REDIS_MAIN"
  fi
else
  echo "redis: missing ${REDIS_MAIN}; is redis-server installed?" >&2
  exit 1
fi

systemctl daemon-reload
systemctl enable redis-server
if ! systemctl restart redis-server; then
  echo "redis: systemctl restart redis-server failed. Recent logs:" >&2
  systemctl status redis-server --no-pager 2>&1 | head -40 >&2 || true
  journalctl -u redis-server -n 40 --no-pager 2>&1 >&2 || true
  exit 1
fi

echo "Redis installed. bind=${BIND} port=${PORT} auth_mode=${AUTH_MODE}"
if [[ "$AUTH_MODE" == "acl" ]]; then
  echo "ACL user: ${ACL_USER}"
fi
if [[ -z "${PIRATE_REDIS_PASSWORD:-}" ]]; then
  echo "PIRATE_REDIS_GENERATED_PASSWORD=${PASSWORD}"
fi
